name: Pull Request Activity Types

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Display PR Activity Info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Action Type: ${{ github.event.action }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "Triggered by: ${{ github.actor }}"
