name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # allows manual trigger from GitHub UI

jobs:
  setup:
    name: Setup Project
    runs-on: ubuntu-latest
    environment: development
    timeout-minutes: 10
    outputs:
      node-version: ${{ steps.set-node.outputs.node-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        id: set-node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        # Output value for downstream jobs
        env:
          CUSTOM_ENV: custom_value

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: setup
    env:
      NODE_ENV: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        node: [16, 18]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and build
        run: |
          npm ci
          npm run build

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: production
      url: https://myapp.example.com
    concurrency:
      group: deploy-production
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy app
        run: echo " Deploying app..."  
