name : my first workflow

on : [push , pull_request_review] 

jobs:
  linux-os:
   runs-on: ubuntu-latest
   steps: 
     - name: Checkout
       uses: actions/checkout@v4.2.2
     - name: Setup Java JDK
       uses: actions/setup-java@v4
       with:
         distribution: 'oracle' 
         java-version: 17
     - name: verify the java version
       run : java -version
     
         
