name: Matrix 

on:
  workflow_dispatch:
  push:
    branches:
      - main
    branches-ignore:
       - dev
       - prod
       
jobs:
  matrix-echo:
    runs-on: ${{matrix.os}}
    strategy:
     fail-fast: false
     matrix:
         os: [ubuntu-latest, windows-latest]
         python-version: [3.9,3.8]
    steps:
      - name: "Matrix Usage"
      - uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v2
        with: 
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Perform Test
        run: echo "Display the ${{matrix.python-version}} and ${{matrix.os}}"
