name: vars contexts

on : 
  workflow_dispatch:
env:
  my_username: ${{vars.username}}
  API_KEY: ${{secrets.API_KEY}}
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
     - name: "Display Info"
       run: |
         echo my username is "${{env.my_username}}"
         echo my API_key is "${{env.API_KEY}}"
   
